name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env create --file environment.yml --name base
        find / -type f -name conda.sh
        source activate
        export PATH="/opt/conda/bin:$PATH"
        which conda
        eval "$(conda shell.bash hook)"
        $CONDA/bin/conda activate base
    - name: install yarn
      run: |
        conda install -c conda-forge yarn=3.5.0
        which yarn
        /usr/share/miniconda/bin/yarn upgrade-interactive
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: yarn Build
      run: |
        /usr/share/miniconda/bin/yarn build
        # conda install pytest
        # pytest
