name: Python Package Using Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"] 
    defaults:
      run:
        shell: "bash -l {0}"
        
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        # https://github.com/marketplace/actions/setup-miniconda
      - name: Install dependencies
        run: |
            conda deactivate
            conda remove -y --all -n datalayer
            # $CONDA is an environment variable pointing to the root of the miniconda directory
            $CONDA/bin/conda init bash
            $CONDA/bin/conda env update --file environment.yml
            $CONDA/bin/conda info
            $CONDA/bin/conda list
            
      - name: Conda Active
        run:  |
            ps -p $$
            whereis conda
            #whereis conda
            #source /usr/share/miniconda/etc/profile.d/conda.sh
            conda activate datalayer
            $CONDA/bin/conda info
      - name: Installation of yarn
        run:  |
            #npm uninstall --global yarn
            corepack enable
            corepack prepare yarn@3.5.0 --activate
    
      - name: Yarn install
        run:  |
            yarn --version
            node --version
            npm --version
            #yarn install
            #conda upgrade yarn
            #npm uninstall --global yarn; npm install --global yarn@3.5.0
            #yarn upgrade 3.5.0
            #npm upgrade
            yarn --version
      - name: Yarn Build Process
        run:  |
            conda install -c conda-forge jupyterlab@4.0.2
            #pip3 install jupyterlab
            conda list jupyterlab
            which jupyter-lab
            #jupyterlab --version
            yarn install
            yarn build
      
