name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: conda-incubator/setup-miniconda@v2
    - name: Set up Python 3.8
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        environment-file: environment.yml
        python-version: 3.8
        auto-activate-base: true
    - shell: bash
      run: |
        conda info
        conda list    
  
