name: Python Package Using Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Conda dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: datalayer
        environment-file: environment.yml
        python-version: 3.7
        auto-activate-base: false
    - name: Conda info
      run: |
        conda info
        conda list
