name: Python Package Using Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]
        
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        # https://github.com/marketplace/actions/setup-miniconda
      - name: Install dependencies
        run: |
            # $CONDA is an environment variable pointing to the root of the miniconda directory
            $CONDA/bin/conda env update --file environment.yml --name base
            $CONDA/bin/conda info
            $CONDA/bin/conda list
      - name: Conda Active
        run:  |
            $CONDA/bin/conda activate base
