name: Python Package Using Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        apt update -y
        source ~/.bashrc
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Set up Conda environment
      run: |
          export PATH="./:$PATH"
          conda init bash
    - name: Perform Conda tests
      run: |
        export PATH="./:$PATH"
        conda activate base
        echo "Conda prefix: $CONDA_PREFIX"
  
